import { http, HttpResponse } from "msw";

const API_BASE = "http://localhost:3001/api/v1";

// Feature-specific handlers land here as PR3/PR4 add component tests.
// Contract-verified handlers should read from `src/mocks/fixtures/generated/`
// (generated by `bundle exec rake contracts:export` in api/, committed to git —
// see docs/adr/0002-generated-contract-fixtures.md) rather than hand-authored
// response bodies, so a payload-shape change in the API fails a build instead
// of silently drifting from what the frontend assumes.
export const handlers = [
    http.get(`${API_BASE}/health`, () => HttpResponse.json({ data: { status: "ok" } })),
];
